# Generated by Django 5.2.17 on 2026-08-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('pk', models.CompositePrimaryKey('region_id', 'type_id', 'date', blank=True, editable=False, primary_key=True, serialize=False)),
                ('region_id', models.BigIntegerField()),
                ('type_id', models.BigIntegerField()),
                ('date', models.DateField()),
                ('average', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('highest', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('lowest', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('volume', models.BigIntegerField()),
                ('order_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'market"."history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('pk', models.CompositePrimaryKey('region_id', 'order_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('region_id', models.BigIntegerField()),
                ('order_id', models.BigIntegerField()),
                ('type_id', models.BigIntegerField()),
                ('location_id', models.BigIntegerField()),
                ('system_id', models.BigIntegerField()),
                ('is_buy_order', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_remain', models.BigIntegerField()),
                ('volume_total', models.BigIntegerField()),
                ('min_volume', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('range', models.TextField()),
                ('issued', models.DateTimeField()),
            ],
            options={
                'db_table': 'market"."orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdersHub',
            fields=[
                ('pk', models.CompositePrimaryKey('region_id', 'order_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('region_id', models.BigIntegerField()),
                ('order_id', models.BigIntegerField()),
                ('type_id', models.BigIntegerField()),
                ('location_id', models.BigIntegerField()),
                ('system_id', models.BigIntegerField()),
                ('is_buy_order', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume_remain', models.BigIntegerField()),
                ('volume_total', models.BigIntegerField()),
                ('min_volume', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('range', models.TextField()),
                ('issued', models.DateTimeField()),
                ('is_in_trade_hub_range', models.BooleanField()),
            ],
            options={
                'db_table': 'orders_hub',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionStatus',
            fields=[
                ('region_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('region_name', models.TextField()),
                ('refreshed_at', models.DateTimeField(null=True)),
                ('order_count', models.BigIntegerField(null=True)),
                ('consecutive_errors', models.IntegerField()),
                ('last_error', models.TextField(null=True)),
                ('last_error_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'market"."region_status',
                'managed': False,
            },
        ),
    ]
