# Generated by Django 5.1.6 on 2026-07-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapSolarSystem',
            fields=[
                ('system_id', models.BigIntegerField(db_column='_key', primary_key=True, serialize=False)),
                ('region_id', models.BigIntegerField()),
                ('name', models.CharField(db_column='name_en', max_length=256)),
            ],
            options={
                'db_table': 'sde"."map_solar_systems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarketGroup',
            fields=[
                ('market_group_id', models.BigIntegerField(db_column='_key', primary_key=True, serialize=False)),
                ('parent_group_id', models.BigIntegerField(null=True)),
                ('name', models.CharField(db_column='name_en', max_length=512)),
                ('has_types', models.BooleanField()),
            ],
            options={
                'db_table': 'sde"."market_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NpcCorporation',
            fields=[
                ('corporation_id', models.BigIntegerField(db_column='_key', primary_key=True, serialize=False)),
                ('faction_id', models.BigIntegerField(null=True)),
                ('name', models.CharField(db_column='name_en', max_length=256)),
            ],
            options={
                'db_table': 'sde"."npc_corporations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.BigIntegerField(db_column='_key', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_en', max_length=512)),
                ('group_id', models.BigIntegerField()),
                ('market_group_id', models.BigIntegerField(null=True)),
                ('meta_group_id', models.IntegerField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('portion_size', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'sde"."types',
                'managed': False,
            },
        ),
    ]
