# Generated by Django 5.2.17 on 2026-08-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpcStationName',
            fields=[
                ('station_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'sde"."npc_station_names',
                'managed': False,
            },
        ),
    ]
