# Generated by Django 5.2.17 on 2026-08-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0002_npcstationname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaGroup',
            fields=[
                ('meta_group_id', models.BigIntegerField(db_column='_key', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_en', max_length=256)),
            ],
            options={
                'db_table': 'sde"."meta_groups',
                'managed': False,
            },
        ),
    ]
