# Generated by Django 5.2.17 on 2026-08-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evesde', '0003_metagroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigIntegerField(db_column='_key', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_en', max_length=512)),
            ],
            options={
                'db_table': 'sde"."categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DogmaAttribute',
            fields=[
                ('attribute_id', models.BigIntegerField(db_column='_key', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('display_name', models.CharField(db_column='display_name_en', max_length=256, null=True)),
                ('unit_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'sde"."dogma_attributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DogmaUnit',
            fields=[
                ('unit_id', models.BigIntegerField(db_column='_key', primary_key=True, serialize=False)),
                ('display_name', models.CharField(db_column='display_name_en', max_length=256, null=True)),
            ],
            options={
                'db_table': 'sde"."dogma_units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.BigIntegerField(db_column='_key', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_en', max_length=512)),
                ('category_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'sde"."groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeBonusMiscBonus',
            fields=[
                ('pk', models.CompositePrimaryKey('type_id', 'ordinal', blank=True, editable=False, primary_key=True, serialize=False)),
                ('type_id', models.BigIntegerField(db_column='_parent_key')),
                ('ordinal', models.IntegerField(db_column='_ordinal_1')),
                ('bonus', models.FloatField(null=True)),
                ('bonus_text', models.TextField(db_column='bonus_text_en')),
                ('importance', models.IntegerField(null=True)),
                ('unit_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'sde"."type_bonus__misc_bonuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeBonusRoleBonus',
            fields=[
                ('pk', models.CompositePrimaryKey('type_id', 'ordinal', blank=True, editable=False, primary_key=True, serialize=False)),
                ('type_id', models.BigIntegerField(db_column='_parent_key')),
                ('ordinal', models.IntegerField(db_column='_ordinal_1')),
                ('bonus', models.FloatField(null=True)),
                ('bonus_text', models.TextField(db_column='bonus_text_en')),
                ('importance', models.IntegerField(null=True)),
                ('unit_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'sde"."type_bonus__role_bonuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeBonusSkill',
            fields=[
                ('pk', models.CompositePrimaryKey('type_id', 'ordinal', blank=True, editable=False, primary_key=True, serialize=False)),
                ('type_id', models.BigIntegerField(db_column='_parent_key')),
                ('ordinal', models.IntegerField(db_column='_ordinal_1')),
                ('skill_type_id', models.BigIntegerField(db_column='_key')),
            ],
            options={
                'db_table': 'sde"."type_bonus__types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeBonusSkillBonus',
            fields=[
                ('pk', models.CompositePrimaryKey('type_id', 'ordinal', 'sub_ordinal', blank=True, editable=False, primary_key=True, serialize=False)),
                ('type_id', models.BigIntegerField(db_column='_parent_key')),
                ('ordinal', models.IntegerField(db_column='_ordinal_1')),
                ('sub_ordinal', models.IntegerField(db_column='_ordinal_2')),
                ('bonus', models.FloatField(null=True)),
                ('bonus_text', models.TextField(db_column='bonus_text_en')),
                ('importance', models.IntegerField(null=True)),
                ('unit_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'sde"."type_bonus__types___value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeDogmaAttribute',
            fields=[
                ('pk', models.CompositePrimaryKey('type_id', 'ordinal', blank=True, editable=False, primary_key=True, serialize=False)),
                ('type_id', models.BigIntegerField(db_column='_parent_key')),
                ('ordinal', models.IntegerField(db_column='_ordinal_1')),
                ('attribute_id', models.BigIntegerField()),
                ('value', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'sde"."type_dogma__dogma_attributes',
                'managed': False,
            },
        ),
    ]
