# Generated by Django 5.0.4 on 2025-02-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('character_name', models.CharField(max_length=128)),
            ],
        ),
    ]
