# Generated by Django 5.1.6 on 2025-03-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helion', '0002_character_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
