# Generated by Django 5.0.4 on 2024-04-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=2048)),
                ('expires_in', models.FloatField(default=0.0)),
                ('token_type', models.CharField(max_length=128)),
                ('refresh_token', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(default=0)),
                ('character_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('is_buy_order', models.BooleanField()),
                ('issued', models.DateTimeField()),
                ('location_id', models.BigIntegerField()),
                ('min_volume', models.IntegerField()),
                ('order_id', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('range', models.CharField(max_length=128)),
                ('system_id', models.BigIntegerField()),
                ('type_id', models.BigIntegerField()),
                ('volume_remain', models.IntegerField()),
                ('volume_total', models.IntegerField()),
                ('region_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
