# Generated by Django 5.1.6 on 2025-03-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('is_buy_order', models.BooleanField(default=False)),
                ('issued', models.DateTimeField()),
                ('location_id', models.BigIntegerField(db_index=True)),
                ('min_volume', models.IntegerField()),
                ('price', models.FloatField(db_index=True)),
                ('range', models.CharField(max_length=128)),
                ('system_id', models.BigIntegerField()),
                ('type_id', models.BigIntegerField(db_index=True)),
                ('volume_remain', models.IntegerField()),
                ('volume_total', models.IntegerField()),
                ('region_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_in_trade_hub_range', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketRegionStatus',
            fields=[
                ('region_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=128)),
                ('orders', models.BigIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('station_id', models.BigIntegerField()),
                ('region_id', models.BigIntegerField()),
                ('system_id', models.BigIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('group_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('market_group_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletJournal',
            fields=[
                ('journal_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('character_id', models.BigIntegerField(db_index=True)),
                ('amount', models.FloatField()),
                ('balance', models.FloatField()),
                ('date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('first_party_id', models.BigIntegerField(blank=True, null=True)),
                ('second_party_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=512, null=True)),
                ('ref_type', models.CharField(db_index=True, max_length=128)),
                ('context_id', models.BigIntegerField(blank=True, null=True)),
                ('context_id_type', models.CharField(blank=True, max_length=128, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('tax_receiver_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.BigIntegerField()),
                ('region_id', models.BigIntegerField()),
                ('date', models.DateField(db_index=True)),
                ('average', models.FloatField()),
                ('highest', models.FloatField()),
                ('lowest', models.FloatField()),
                ('order_count', models.BigIntegerField()),
                ('volume', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['type_id', 'region_id'], name='market_mark_type_id_1b69cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketTransaction',
            fields=[
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('character_id', models.BigIntegerField(db_index=True)),
                ('client_id', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('is_buy', models.BooleanField()),
                ('is_personal', models.BooleanField()),
                ('journal_ref_id', models.BigIntegerField()),
                ('location_id', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('type_id', models.BigIntegerField()),
                ('unit_price', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['is_buy', 'location_id', 'type_id'], name='market_mark_is_buy_5411a4_idx')],
            },
        ),
    ]
