# Generated by Django 5.1.6 on 2025-03-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(db_index=True)),
                ('event_type', models.CharField(max_length=32)),
                ('notification_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='marketorder',
            name='character_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
