# Generated by Django 5.0.4 on 2024-04-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_marketregionstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('name', models.CharField(max_length=512)),
            ],
        ),
    ]
