# Generated by Django 5.1.6 on 2025-03-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_marketnotification_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketOrderUndercut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.BigIntegerField(db_index=True)),
                ('region_id', models.BigIntegerField(db_index=True)),
                ('character_id', models.BigIntegerField(db_index=True)),
                ('order_id', models.BigIntegerField()),
                ('order_price', models.FloatField()),
                ('order_issued', models.DateTimeField()),
                ('competitor_order_id', models.BigIntegerField()),
                ('competitor_price', models.FloatField()),
                ('competitor_issued', models.DateTimeField()),
                ('is_buy_order', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order_id', 'order_issued'), name='uc_order_modification')],
                'unique_together': {('order_id', 'order_issued')},
            },
        ),
    ]
