# Generated by Django 5.1.6 on 2025-03-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_marketorderundercut'),
    ]

    operations = [
        migrations.CreateModel(
            name='A4EMarketHistoryVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.BigIntegerField()),
                ('type_id', models.BigIntegerField()),
                ('date', models.DateField()),
                ('order_count', models.IntegerField()),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'db_table': 'a4e_market_history_volume',
                'managed': False,
            },
        ),
    ]
