# Generated by Django 5.1.6 on 2026-07-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_a4emarkethistoryvolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHubJumps',
            fields=[
                ('system_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('jumps_to_trade_hub', models.IntegerField()),
            ],
        ),
    ]
