# Generated by Django 5.0.4 on 2024-04-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_remove_character_id_remove_marketorder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketorder',
            name='location_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='price',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='type_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
