# Generated by Django 5.2.17 on 2026-08-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_backfill_system_hub_jumps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markethistory',
            name='average',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='highest',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='lowest',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='markethistory',
            name='volume',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='volume_remain',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='volume_total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='marketorderundercut',
            name='competitor_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='marketorderundercut',
            name='order_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='markettransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='walletjournal',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='walletjournal',
            name='balance',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='walletjournal',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='markethistory',
            constraint=models.UniqueConstraint(fields=('region_id', 'type_id', 'date'), name='uq_markethistory_region_type_date'),
        ),
    ]
