# Generated by Django 5.0.4 on 2024-04-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_marketorder_location_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='markettransaction',
            index=models.Index(fields=['is_buy', 'location_id', 'type_id'], name='market_mark_is_buy_5411a4_idx'),
        ),
    ]
