# Generated by Django 5.0.4 on 2024-04-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_markettransaction_market_mark_is_buy_5411a4_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdeTypeId',
            fields=[
                ('type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('group_id', models.BigIntegerField(db_index=True)),
                ('market_group_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(max_length=512)),
            ],
        ),
    ]
