# Generated by Django 5.2.17 on 2026-08-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_markethistory_average_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketorderundercut',
            unique_together=set(),
        ),
    ]
