# Generated by Django 5.0.4 on 2024-04-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_sdetypeid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SdeTypeId',
        ),
    ]
