# Generated by Django 5.2.17 on 2026-08-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_alter_marketorderundercut_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A4EMarketHistoryVolume',
        ),
        # The model was unmanaged, so DeleteModel is state-only; the table
        # (loaded externally from adam4eve CSVs) must be dropped explicitly.
        migrations.RunSQL("DROP TABLE IF EXISTS a4e_market_history_volume"),
    ]
