# Generated by Django 5.0.4 on 2024-04-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_delete_sdetypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeitem',
            name='group_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeitem',
            name='market_group_id',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
