# Generated by Django 5.2.17 on 2026-08-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_delete_a4emarkethistoryvolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterOrder',
            fields=[
                ('order_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('character_id', models.BigIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=128, unique=True)),
                ('tracks', models.CharField(default='orders', max_length=128)),
            ],
        ),
    ]
