# Generated by Django 5.0.4 on 2024-04-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_tradeitem_group_id_tradeitem_market_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitem',
            name='group_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='market_group_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
    ]
