# Generated by Django 5.2.17 on 2026-08-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_characterorder_trackedcharacter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAsset',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('character_id', models.BigIntegerField(db_index=True)),
                ('type_id', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('location_id', models.BigIntegerField()),
                ('location_type', models.CharField(max_length=32)),
                ('location_flag', models.CharField(max_length=64)),
                ('is_singleton', models.BooleanField()),
                ('is_blueprint_copy', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EsiFetchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=128)),
                ('feed', models.CharField(max_length=16)),
                ('next_due', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('consecutive_errors', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('character_name', 'feed'), name='uc_fetch_state')],
            },
        ),
    ]
