# Generated by Django 5.2.17 on 2026-08-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_characterasset_esifetchstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketHistory',
        ),
        migrations.DeleteModel(
            name='MarketNotification',
        ),
        migrations.DeleteModel(
            name='MarketOrder',
        ),
        migrations.DeleteModel(
            name='MarketRegionStatus',
        ),
    ]
