# Generated by Django 5.0.4 on 2024-04-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_tradeitem_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitem',
            name='group_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='market_group_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
