# Generated by Django 5.2.17 on 2026-08-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_delete_markethistory_delete_marketnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterContract',
            fields=[
                ('contract_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('acceptor_id', models.BigIntegerField()),
                ('assignee_id', models.BigIntegerField()),
                ('issuer_id', models.BigIntegerField()),
                ('issuer_corporation_id', models.BigIntegerField()),
                ('availability', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('for_corporation', models.BooleanField()),
                ('start_location_id', models.BigIntegerField(blank=True, null=True)),
                ('end_location_id', models.BigIntegerField(blank=True, null=True)),
                ('buyout', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('collateral', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('reward', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('days_to_complete', models.IntegerField(blank=True, null=True)),
                ('date_issued', models.DateTimeField()),
                ('date_expired', models.DateTimeField()),
                ('date_accepted', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EveName',
            fields=[
                ('entity_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('category', models.CharField(max_length=32)),
                ('resolved_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
