# Generated by Django 5.2.17 on 2026-08-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_charactercontract_evename'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterasset',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
