# Generated by Django 5.0.4 on 2024-05-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_tradeitem_group_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('region_id', models.IntegerField()),
                ('average', models.FloatField()),
                ('date', models.DateField(db_index=True)),
                ('highest', models.FloatField()),
                ('lowest', models.FloatField()),
                ('order_count', models.IntegerField()),
                ('volume', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['type_id', 'region_id'], name='market_mark_type_id_1b69cf_idx')],
            },
        ),
    ]
