# Generated by Django 5.0.4 on 2024-05-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_markethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='authdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
