# Generated by Django 5.2.17 on 2026-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_characterasset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterasset',
            name='corporation_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='characterorder',
            name='corporation_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='characterorder',
            name='is_corporation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketorderundercut',
            name='corporation_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='markettransaction',
            name='corporation_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='markettransaction',
            name='division',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletjournal',
            name='corporation_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='walletjournal',
            name='division',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='characterasset',
            name='character_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='characterorder',
            name='character_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketorderundercut',
            name='character_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='markettransaction',
            name='character_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='walletjournal',
            name='character_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
