# Generated by Django 5.0.4 on 2024-05-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_authdata_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehub',
            name='system_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
