# Generated by Django 5.2.17 on 2026-08-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_characterasset_corporation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedcharacter',
            name='is_trader',
            field=models.BooleanField(default=True),
        ),
    ]
