# Generated by Django 5.2.17 on 2026-08-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_trackedcharacter_is_trader'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.BigIntegerField(db_index=True)),
                ('region_id', models.BigIntegerField(blank=True, null=True)),
                ('hubs_only', models.BooleanField(default=False)),
                ('side', models.CharField(choices=[('ask', 'ask'), ('bid', 'bid')], max_length=3)),
                ('operator', models.CharField(choices=[('>=', '>='), ('<', '<')], max_length=2)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_triggered', models.BooleanField(default=False)),
                ('triggered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('triggered_region_id', models.BigIntegerField(blank=True, null=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type_id', 'region_id', 'hubs_only', 'side', 'operator', 'threshold'), name='uc_price_alert', nulls_distinct=False)],
            },
        ),
    ]
