# Generated by Django 5.2.17 on 2026-08-26 05:58

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_pricealert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uc_shopping_list_name')],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('quantity', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='market.shoppinglist')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('shopping_list'), name='uc_shopping_list_item_name')],
            },
        ),
    ]
