# Generated by Django 5.0.4 on 2024-05-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_marketstructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketorder',
            name='is_in_trade_hub_range',
            field=models.BooleanField(default=True),
        ),
    ]
