# Generated by Django 5.0.4 on 2024-05-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_marketorder_is_in_trade_hub_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletJournal',
            fields=[
                ('journal_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('balance', models.FloatField()),
                ('date', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('first_party_id', models.BigIntegerField(blank=True, null=True)),
                ('second_party_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=512, null=True)),
                ('ref_type', models.CharField(max_length=128)),
                ('context_id', models.BigIntegerField(blank=True, null=True)),
                ('context_id_type', models.CharField(blank=True, max_length=128, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('tax_receiver_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
