# Generated by Django 5.0.4 on 2024-05-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_walletjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletjournal',
            name='ref_type',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
