# Generated by Django 5.1.6 on 2025-03-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_alter_walletjournal_ref_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketorder',
            name='is_buy_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marketorder',
            name='price',
            field=models.FloatField(db_index=True),
        ),
    ]
