# Generated by Django 5.1.6 on 2025-03-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0023_alter_marketorder_is_buy_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markettransaction',
            name='character_id',
            field=models.BigIntegerField(db_index=True, default=91731013),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walletjournal',
            name='character_id',
            field=models.BigIntegerField(db_index=True, default=91731013),
            preserve_default=False,
        ),
    ]
