# Generated by Django 5.1.6 on 2025-03-07 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_markettransaction_character_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthData',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='MarketStructure',
        ),
    ]
