# Generated by Django 5.1.6 on 2025-03-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketGroup',
            fields=[
                ('market_group_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('has_types', models.BooleanField()),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
                ('parent_group_id', models.BigIntegerField(blank=True, db_index=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NpcCorporation',
            fields=[
                ('corporation_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('faction_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('name', models.CharField(db_index=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SdeTypeId',
            fields=[
                ('type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('group_id', models.BigIntegerField(db_index=True)),
                ('meta_id', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
                ('market_group_id', models.BigIntegerField(blank=True, db_index=True, default=None, null=True)),
                ('name', models.CharField(max_length=512)),
                ('volume', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('system_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('constellation_id', models.BigIntegerField()),
                ('region_id', models.BigIntegerField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('security', models.FloatField()),
                ('security_class', models.CharField(max_length=3)),
                ('jumps_to_trade_hub', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
            ],
        ),
    ]
