# Generated by Django 5.0.4 on 2024-04-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketGroup',
            fields=[
                ('market_group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('has_types', models.BooleanField()),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
                ('parent_group_id', models.IntegerField(db_index=True)),
            ],
        ),
    ]
