# Generated by Django 5.1.6 on 2025-03-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.BigIntegerField()),
                ('material_type_id', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('type_id', 'material_type_id'), name='pk_type_material')],
                'unique_together': {('type_id', 'material_type_id')},
            },
        ),
    ]
