# Generated by Django 5.0.4 on 2024-04-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0002_marketgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketgroup',
            name='parent_group_id',
            field=models.BigIntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
