# Generated by Django 5.1.6 on 2025-03-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0002_typematerials'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdetypeid',
            name='portion_size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
