# Generated by Django 5.0.4 on 2024-04-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0003_alter_marketgroup_parent_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdetypeid',
            name='meta_id',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
