# Generated by Django 5.0.4 on 2024-05-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0004_sdetypeid_meta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdetypeid',
            name='volume',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
