# Generated by Django 5.0.4 on 2024-05-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0005_sdetypeid_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetypeid',
            name='volume',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
