# Generated by Django 5.0.4 on 2024-05-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0008_alter_npccorporation_faction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npccorporation',
            name='faction_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
