# Generated by Django 5.0.4 on 2024-05-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0009_alter_npccorporation_faction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdetypeid',
            name='market_group_id',
            field=models.BigIntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
